cache-prompts: true
gitignore: false
read:
  - conventions.md
  - ~/instructions.md
architect: true
model: sonnet
thinking-tokens: 8k
editor-model: anthropic/claude-3-7-sonnet-latest
watch-files: true
map-tokens: 0
auto-accept-architect: false
