cache-prompts: true
gitignore: false
read:
  - conventions.md
  - ~/instructions.md
architect: true
model: sonnet
thinking-tokens: 8000
editor-model: claude-3-5-sonnet-latest
watch-files: true
map-tokens: 0
auto-accept-architect: false
