k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  ui:
    skin: catppuccin-mocha
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: production-shop-eks-green
  currentCluster: arn:aws:eks:eu-central-1:790545514541:cluster/production-shop-eks-green
  clusters:
    arn:aws:eks:eu-central-1:790545514541:cluster/production-shop-eks-green:
      namespace:
        active: jq-shop-production
        lockFavorites: false
        favorites:
        - jq-shop-production
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/z8/hyxdk1kd3y1g9ln54lb6htgdx23vnp/T/k9s-screens-aleksandr.kirillov
